version: "3.9"
services:
  brain:
    build:
      context: .
      dockerfile: Dockerfile.brain.dev
    container_name: brain
    volumes:
      - .:/app
    environment:
      - NETWORK=holesky
      - _DAPPNODE_GLOBAL_CONSENSUS_CLIENT_HOLESKY=lighthouse-holesky.dnp.dappnode.eth
      - _DAPPNODE_GLOBAL_EXECUTION_CLIENT_HOLESKY=holesky-geth.dnp.dappnode.eth
      - _DAPPNODE_GLOBAL_MEVBOOST_HOLESKY=true

    networks:
      dncore_network:
        aliases:
          - brain.web3signer-holesky.dappnode

networks:
  dncore_network:
    external: true
