ARG DOCKER_IMAGE=20.17.0-alpine.3.20

###############
# BUILD stage #
###############
FROM ${DOCKER_IMAGE} as build-stage

# Fixes error on `react-scripts-build`
# error:0308010C:digital envelope routines::unsupported https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
ENV NODE_OPTIONS=--openssl-legacy-provider
ENV NODE_ENV=development

RUN apk add --no-cache --virtual .build-deps \
  build-base \
  python3 \
  git \
  && apk add --no-cache \
  bash \
  curl \
  && rm -rf /var/cache/apk/*

COPY entrypoint-dev.sh /usr/local/bin/entrypoint-dev.sh

ENTRYPOINT [ "/usr/local/bin/entrypoint-dev.sh" ]