version: "3.9"
services:
  brain:
    build:
      context: .
      dockerfile: Dockerfile.brain.dev
    container_name: DAppNodePackage-brain.web3signer-hoodi.dnp.dappnode.eth
    volumes:
      - .:/app
    environment:
      - NETWORK=hoodi
      - _DAPPNODE_GLOBAL_CONSENSUS_CLIENT_HOODI=lighthouse-hoodi.dnp.dappnode.eth
      - _DAPPNODE_GLOBAL_EXECUTION_CLIENT_HOODI=hoodi-geth.dnp.dappnode.eth
      - _DAPPNODE_GLOBAL_MEVBOOST_HOODI=true

    networks:
      dncore_network:
        aliases:
          - brain.web3signer-hoodi.dappnode

networks:
  dncore_network:
    external: true
