version: "3.8"
services:
  brain:
    build:
      context: .
      dockerfile: Dockerfile.brain.dev
    container_name: braindev
    volumes:
      - .:/app
    environment:
      - NETWORK=holesky
      - _DAPPNODE_CONSENSUS_CLIENT_PRATER=lighthouse-holesky.dnp.dappnode.eth
      - _DAPPNODE_EXECUTION_CLIENT_PRATER_VERSION=holesky-geth.dnp.dappnode.eth
    networks:
      dncore_network:
        aliases:
          - brain.web3signer-holesky.dappnode

networks:
  dncore_network:
    external: true
