FROM gcr.io/prysmaticlabs/prysm/validator:latest

RUN echo "api-token-0x0200e6ce18e26fd38caca7ae1bfb9e2bba7efb20ed2746ad17f2f6dda44603152d" > /root/.lighthouse/validators/api-token.txt

CMD ["validator", "--prater", "--datadir=/data", "--wallet-dir=/root/.eth2validators", "--beacon-rpc-provider=beacon-chain.prysm-prater.dappnode:4000", "--beacon-rpc-gateway-provider=beacon-chain.prysm-prater.dappnode:3500", "--validators-external-signer-url=http://web3signer.web3signer-prater.dappnode:9000", "--grpc-gateway-host=0.0.0.0", "--grpc-gateway-port=3500", "--grpc-gateway-corsdomain=http://0.0.0.0:3500", "--graffiti=validating_from_DAppNode", "--suggested-fee-recipient=0x0000000000000000000000000000000000000000", "--web", "--accept-terms-of-use", "--enable-doppelganger"]