ARG DOCKER_IMAGE=node:20.17.0-alpine3.20
FROM --platform=$TARGETPLATFORM ${DOCKER_IMAGE} as build-stage

ENV NODE_ENV=development
WORKDIR /app

RUN apk add --no-cache --virtual .build-deps \
  build-base \
  python3 \
  git \
  && apk add --no-cache \
  bash \
  curl \
  && rm -rf /var/cache/apk/*

RUN corepack enable && yarn set version berry

ENTRYPOINT ["/bin/bash", "-c", "yarn && yarn build && yarn run dev"]