version: "3.8"
services:
  brain:
    build:
      context: .
      dockerfile: Dockerfile.brain.dev
    container_name: brain
    volumes:
      - .:/app
    environment:
      - NETWORK=prater
      - _DAPPNODE_CONSENSUS_CLIENT_MAINNET=teku.dnp.dappnode.eth
      - _DAPPNODE_EXECUTION_CLIENT_MAINNET_VERSION=geth.dnp.dappnode.eth
      - _DAPPNODE_CONSENSUS_CLIENT_PRATER=teku-prater.dnp.dappnode.eth
      - _DAPPNODE_EXECUTION_CLIENT_PRATER_VERSION=goerli-geth.dnp.dappnode.eth
    networks:
      dncore_network:
        aliases:
          - brain.web3signer-prater.dappnode

  signer:
    image: consensys/web3signer:latest
    depends_on:
      - db
    security_opt:
      - "seccomp:unconfined"
    container_name: signer
    command:
      [
        "--key-store-path=/keystores",
        "--http-listen-port=9000",
        "--http-listen-host=0.0.0.0",
        "--http-host-allowlist=validator.prysm-prater.dappnode,brain.web3signer-prater.dappnode",
        "--http-cors-origins=*",
        "--idle-connection-timeout-seconds=90",
        "eth2",
        "--network=prater",
        "--slashing-protection-db-url=jdbc:postgresql://postgres.web3signer-prater.dappnode:5432/web3signer-prater",
        "--slashing-protection-db-username=postgres",
        "--slashing-protection-db-password=prater",
        "--key-manager-api-enabled=true",
      ]
    networks:
      dncore_network:
        aliases:
          - web3signer.web3signer-prater.dappnode

  db:
    build:
      context: .
      dockerfile: Dockerfile.db.dev
      args:
        UPSTREAM_VERSION: 23.1.0
    container_name: signer-db
    command: postgres
    user: postgres
    healthcheck:
      test: pg_isready -U postgres
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      dncore_network:
        aliases:
          - postgres.web3signer-prater.dappnode

  prysm-validator:
    container_name: prysm-validator
    build:
      context: .
      dockerfile: Dockerfile.prysm.dev
    networks:
      dncore_network:
        aliases:
          - validator.prysm-prater.dappnode

  lighthouse-validator:
    container_name: lighthouse-validator
    security_opt:
      - "seccomp:unconfined"
    build:
      context: .
      dockerfile: Dockerfile.lighthouse.dev
    networks:
      dncore_network:
        aliases:
          - validator.lighthouse-prater.dappnode

  teku-validator:
    container_name: teku-validator
    build:
      context: .
      dockerfile: Dockerfile.teku.dev
    networks:
      dncore_network:
        aliases:
          - validator.teku-prater.dappnode

networks:
  dncore_network:
    external: true
